import "./globals.css";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Noto_Sans_KR } from "next/font/google";
import GithubIcon from '../../assets/github-icon.png';
import FavIcon from '../../assets/favicon-128.png';

const font = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Johann blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta http-equiv='cache-control' content='no-cache'/> 
        <meta http-equiv='expires' content='0'/> 
        <meta http-equiv='pragma' content='no-cache'/>
      </head>
      <body className={font.className}>
        <div id="body-wrapper">
          <div className="nav-container">
            <div className="nav">
              <div className="menu">
                <Link className="logo" href="/">
                  <Image src={FavIcon} alt='favicon' width={32} height={32} style={{borderRadius:6}}></Image>
                  johann blue
                </Link>
                <a href="https://github.com/johannblue">
                  <Image src={GithubIcon} alt="github" width={32} height={32}/>
                </a>
              </div>
              <input className={font.className} type="text" name="" id="" placeholder="Search..."/>
            </div>
          </div>
          {children}
        </div>
        <footer>
          <p>designed by @johannblue</p>
          <p>powered by github.io</p>
        </footer>
      </body>
    </html>
  );
}
